#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : scummvm
Version  : 2.1.1
Release  : 6
URL      : https://github.com/scummvm/scummvm/archive/v2.1.1/scummvm-2.1.1.tar.gz
Source0  : https://github.com/scummvm/scummvm/archive/v2.1.1/scummvm-2.1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause CC-BY-3.0 GPL-2.0 GPL-3.0 LGPL-2.1 MIT OFL-1.1 PostgreSQL
Requires: scummvm-bin = %{version}-%{release}
Requires: scummvm-data = %{version}-%{release}
Requires: scummvm-license = %{version}-%{release}
Requires: scummvm-man = %{version}-%{release}
BuildRequires : SDL-dev
BuildRequires : SDL_net-dev
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-cpan
BuildRequires : curl-dev
BuildRequires : flac-dev
BuildRequires : freetype-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpng-dev
BuildRequires : libtheora-dev
BuildRequires : libvorbis-dev
BuildRequires : pkgconfig(x11)
BuildRequires : zlib-dev
Patch1: CVE-2014-5461.patch

%description
ScummVM is an interpreter that will play many graphic adventure games,
including LucasArts SCUMM games (such as Monkey Island 1-3, Day of the
Tentacle, Sam & Max, ...), many of Sierra's AGI and SCI games (such as King's
Quest 1-6, Space Quest 1-5, ...), Discworld 1 and 2, Simon the Sorcerer 1 and
2, Beneath A Steel Sky, Lure of the Temptress, Broken Sword 1 and 2, Flight of
the Amazon Queen, Gobliiins 1-3, The Legend of Kyrandia 1-3, many of Humongous
Entertainment's children's SCUMM games (including Freddi Fish and Putt Putt
games) and many more. See https://www.scummvm.org for a full compatibility list.

%package bin
Summary: bin components for the scummvm package.
Group: Binaries
Requires: scummvm-data = %{version}-%{release}
Requires: scummvm-license = %{version}-%{release}

%description bin
bin components for the scummvm package.


%package data
Summary: data components for the scummvm package.
Group: Data

%description data
data components for the scummvm package.


%package doc
Summary: doc components for the scummvm package.
Group: Documentation
Requires: scummvm-man = %{version}-%{release}

%description doc
doc components for the scummvm package.


%package license
Summary: license components for the scummvm package.
Group: Default

%description license
license components for the scummvm package.


%package man
Summary: man components for the scummvm package.
Group: Default

%description man
man components for the scummvm package.


%prep
%setup -q -n scummvm-2.1.1
cd %{_builddir}/scummvm-2.1.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579302031
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static || ./configure --host=x86_64-generic-linux-gnu --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --libdir=/usr/lib64 --mandir=/usr/share/man
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1579302031
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/scummvm
cp %{_builddir}/scummvm-2.1.1/COPYING %{buildroot}/usr/share/package-licenses/scummvm/2b9d60c2972b476384af9900276837ac81954e80
cp %{_builddir}/scummvm-2.1.1/COPYING.BSD %{buildroot}/usr/share/package-licenses/scummvm/da895920d4a7d4f0920fade3570969cf4d5fafd6
cp %{_builddir}/scummvm-2.1.1/COPYING.FREEFONT %{buildroot}/usr/share/package-licenses/scummvm/e58874a433eec4f975f35cb34379712d3b932f9e
cp %{_builddir}/scummvm-2.1.1/COPYING.LGPL %{buildroot}/usr/share/package-licenses/scummvm/091c8f65dffdd24bf8c803d8b97c365d2981bdf5
cp %{_builddir}/scummvm-2.1.1/COPYING.OFL %{buildroot}/usr/share/package-licenses/scummvm/d9a40d0905db5a3d6d1119e0e272ab8018dc092f
cp %{_builddir}/scummvm-2.1.1/common/lua/COPYRIGHT %{buildroot}/usr/share/package-licenses/scummvm/52144cf874618949f7857eb5adb964bf3cd7938f
cp %{_builddir}/scummvm-2.1.1/devtools/tasmrecover/dreamweb/LICENSE %{buildroot}/usr/share/package-licenses/scummvm/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/scummvm-2.1.1/gui/themes/fonts/LICENSE.mplus %{buildroot}/usr/share/package-licenses/scummvm/a70b05899e79e96734d62e59093e646812eba2db
cp %{_builddir}/scummvm-2.1.1/test/cxxtest/COPYING %{buildroot}/usr/share/package-licenses/scummvm/dd4547c72e04fd16fd675556993abb945491a69c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/scummvm

%files data
%defattr(-,root,root,-)
/usr/share/appdata/scummvm.appdata.xml
/usr/share/applications/scummvm.desktop
/usr/share/icons/hicolor/scalable/apps/scummvm.svg
/usr/share/pixmaps/scummvm.xpm
/usr/share/scummvm/access.dat
/usr/share/scummvm/cryomni3d.dat
/usr/share/scummvm/drascula.dat
/usr/share/scummvm/fonts.dat
/usr/share/scummvm/hugo.dat
/usr/share/scummvm/kyra.dat
/usr/share/scummvm/lure.dat
/usr/share/scummvm/mort.dat
/usr/share/scummvm/neverhood.dat
/usr/share/scummvm/pred.dic
/usr/share/scummvm/queen.tbl
/usr/share/scummvm/scummclassic.zip
/usr/share/scummvm/scummmodern.zip
/usr/share/scummvm/scummremastered.zip
/usr/share/scummvm/sky.cpt
/usr/share/scummvm/supernova.dat
/usr/share/scummvm/teenagent.dat
/usr/share/scummvm/tony.dat
/usr/share/scummvm/toon.dat
/usr/share/scummvm/translations.dat
/usr/share/scummvm/wintermute.zip
/usr/share/scummvm/wwwroot.zip
/usr/share/scummvm/xeen.ccs

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/scummvm/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/scummvm/091c8f65dffdd24bf8c803d8b97c365d2981bdf5
/usr/share/package-licenses/scummvm/2b9d60c2972b476384af9900276837ac81954e80
/usr/share/package-licenses/scummvm/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/scummvm/52144cf874618949f7857eb5adb964bf3cd7938f
/usr/share/package-licenses/scummvm/a70b05899e79e96734d62e59093e646812eba2db
/usr/share/package-licenses/scummvm/d9a40d0905db5a3d6d1119e0e272ab8018dc092f
/usr/share/package-licenses/scummvm/da895920d4a7d4f0920fade3570969cf4d5fafd6
/usr/share/package-licenses/scummvm/dd4547c72e04fd16fd675556993abb945491a69c
/usr/share/package-licenses/scummvm/e58874a433eec4f975f35cb34379712d3b932f9e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man6/scummvm.6
